chore(warnings): fix warnings about unused variables in Release mode
```
/home/stephan/projects/Vulkan-Hpp/VulkanHppGenerator.cpp:9105:12: error: unused variable 'constructorCommandIt' [-Werror,-Wunused-variable]
      auto constructorCommandIt = m_commands.find( handle.second.constructorIts.front()->first );
           ^
/home/stephan/projects/Vulkan-Hpp/VulkanHppGenerator.cpp:9732:12: error: unused variable 'handleIt' [-Werror,-Wunused-variable]
      auto handleIt = m_handles.find( "Vk" + parentType );
```